language: generic

sudo: required

addons:
    apt:
        packages:
            - git
            - bash
            - sed
            - realpath
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake

before_script:
    - git clone https://github.com/sstephenson/bats.git $HOME/bats
    - export PATH=$PATH:$HOME/bats/bin

script: make

after_success: |
    git clone https://github.com/forkcon/kcov.git kcov &&
    cd kcov &&
    git checkout fix-bash-script-hanging &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov &&
    mkdir -p coverage &&
    mkdir -p kcov &&
    for test in test/self/*.sh; do 
        test_dir=$(basename $test .sh) &&
        mkdir kcov/$test_dir && kcov --exclude-path=test kcov/$test_dir $test
    done &&
    kcov --merge coverage kcov/* &&
    rm -rf kcov &&
    bash <(curl -s https://codecov.io/bash)
